title: julie's template
email: example@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A decap website template for julie
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: none
github_username:  juilie

plugins:
  - jekyll-feed

include:
  - static